version: '3'
services:
    start:
        image: crooner
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./crontab:/etc/crontab
            - ./stacks:/stacks
        command: start
        environment:
            CROONER_VERBOSE: "yes"
